[project]
name = "embcli-cohere"
version = "0.0.1"
description = "cohere plugin for embcli"
readme = "README.md"
authors = [{ name = "Tomoko Uchida", email = "tomoko.uchida.1111@gmail.com" }]
requires-python = ">=3.10"
dependencies = ["cohere>=5.15.0", "embcli-core"]

[tool.uv.sources]
embcli-core = { workspace = true }

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project.entry-points."embcli"]
cohere = "embcli_cohere.cohere_model"
