[project]
name = "embcli-llamacpp"
version = "0.0.3-dev"
description = "llama-cpp-python plugin for embcli"
readme = "README.md"
authors = [{ name = "Tomoko Uchida", email = "tomoko.uchida.1111@gmail.com" }]
license = { file = "LICENSE.txt" }
keywords = ["cli", "llm", "nlp", "embeddings"]
classifiers = [
    "Development Status :: 2 - Pre-Alpha",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Topic :: Scientific/Engineering :: Artificial Intelligence",
    "Topic :: Terminals",
    "Topic :: Text Processing :: Linguistic",
    "Topic :: Utilities",
]
requires-python = ">=3.10"
dependencies = ["embcli-core>=0.0.8", "llama-cpp-python>=0.3.9"]

[project.urls]
"Repository" = "https://github.com/mocobeta/embcli"

[tool.uv.sources]
embcli-core = { workspace = true }

[project.entry-points."embcli"]
llamacpp = "embcli_llamacpp.llamacpp"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
