[project]
name = "embcli-jina"
version = "0.0.1"
description = "jina plugin for embcli"
readme = "README.md"
authors = [{ name = "Tomoko Uchida", email = "tomoko.uchida.1111@gmail.com" }]
requires-python = ">=3.10"
dependencies = [
    "embcli-core",
    "httpx>=0.28.1",
]

[tool.uv.sources]
embcli-core = { workspace = true }

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project.entry-points."embcli"]
jina = "embcli_jina.jina"
