name: CI for Mistral Models

on: workflow_dispatch

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13"]

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'pip'
    
    - name: Cache uv dependencies
      uses: actions/cache@v4
      with:
        path: ~/.cache/uv
        key: ${{ runner.os }}-uv-${{ hashFiles('pyproject.toml') }}-${{ matrix.python-version }}
        restore-keys: |
          ${{ runner.os }}-uv-
        
    - name: Install dev dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install uv
        uv venv
        
    - name: Lint with ruff
      run: |
        uv run ruff check .
        
    - name: Type check with pyright in embcli-mistral
      run: |
        uv run --package embcli-mistral pyright packages/embcli-mistral/
        
    - name: Test with pytest in embcli-mistral
      env:
        MISTRAL_API_KEY: ${{ secrets.MISTRAL_API_KEY }}
        RUN_MISTRAL_TESTS: "1"
      run: |
        uv run --package embcli-mistral pytest packages/embcli-mistral/tests
