name: Publish Package to PyPI

on: 
  workflow_dispatch:
    inputs:
      testpypi:
        description: 'Publish to TestPyPI'
        required: false
        default: false
        type: boolean
      pypi:
        description: 'Publish to PyPI'
        required: false
        default: false
        type: boolean
      package:
        description: 'Package to publish'
        required: true
        default: 'embcli-core'
        type: choice
        options:
          - embcli-core
          - embcli-cohere
          - embcli-gemini
          - embcli-jina
          - embcli-mistral
          - embcli-openai
          - embcli-sbert
          - embcli-voyage
          - all

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
        cache: 'pip'

    - name: Set up uv
      run: |
        python -m pip install --upgrade pip
        python -m pip install uv
        uv venv
  
    - name: Build the package
      if: inputs.package != 'all'
      run: |
        uv build --package ${{ inputs.package }}
        echo "Package ${{ inputs.package }} built successfully"

    - name: Build all packages
      if: inputs.package == 'all'
      run: |
        uv build --all-packages
        echo "All packages built successfully"
                            
    - name: Publish to TestPyPI
      if: inputs.testpypi == true
      env:
        UV_PUBLISH_TOKEN: ${{ secrets.TESTPYPI_TOKEN }}
      run: |
        uv publish --index testpypi dist/*
        echo "Package published to TestPyPI"
    
    - name: Publish to PyPI
      if: inputs.pypi == true
      env:
        UV_PUBLISH_TOKEN: ${{ secrets.PYPI_TOKEN }}
      run: |
        uv publish dist/*
        echo "Package published to PyPI"
